import { Share, ShareOptions, UniShareProvider } from "../interface.uts";
import {ShareFailImpl} from "../unierror.uts";

export const share : Share = function (options : ShareOptions) {
	const provider = UTSAndroid.getProvider<UniShareProvider>("share", options.provider ?? '');
	if (provider != null) {
		provider.share(options);
	} else {
		// 使用空值合并运算符提供默认值
		const errMsg = '未找到分享服务提供商';
		const err = new ShareFailImpl(4000600);
		options.fail?.(err);
		options.complete?.(err);
	}
};
