import { InnerAudioContext, CreateInnerAudioContext, SetInnerAudioOption, SetInnerAudioOptionOptions,SetInnerAudioOptionSuccess } from "../interface.uts"
import AudioPlayer from "uts.sdk.modules.uniCreateInnerAudioContext.AudioPlayer";
import AudioFocusHelper from "uts.sdk.modules.uniCreateInnerAudioContext.AudioFocusHelper";
export { CreateInnerAudioContextFailImpl } from '../unierror.uts'

export const createInnerAudioContext : CreateInnerAudioContext = function () : InnerAudioContext {
	let player = new AudioPlayer()
	return player
}

export const setInnerAudioOption : SetInnerAudioOption = function (options : SetInnerAudioOptionOptions) {
	var mixWithOther = true
	if (options.mixWithOther == null) {
		mixWithOther = true
	} else {
		mixWithOther = options.mixWithOther!
	}
	AudioFocusHelper.getInstance(UTSAndroid.getAppContext()!).mixWithOther = mixWithOther
	options?.success?.({})
	options?.complete?.({})
}