import { __uniConfig } from '@dcloudio/uni-runtime'
import { GetLaunchOptionsSync, OnLaunchOptions } from './interface.uts'

let launchOptions = { path: __uniConfig.entryPagePath } as OnLaunchOptions

export const setLaunchOptionsSync = function (options: OnLaunchOptions) {
    launchOptions = options
}

export const getLaunchOptionsSync = defineSyncApi<GetLaunchOptionsSync>(
    'getLaunchOptionsSync',
    (): OnLaunchOptions => {
        return launchOptions
    },
)
