
export interface Uni {
    /**
     * 开始  生物认证
	 * @param options 开始生物认证参数
     *
     * @tutorial https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#startsoterauthentication
     * @tutorial_uni_app https://uniapp.dcloud.net.cn/api/system/authentication.html#startsoterauthentication
     * @tutorial_uni_app_x https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#startsoterauthentication
     *
     * @uniPlatform {
     * 	"app": {
     * 		"android": {
     * 			"osVer": "5.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     * 		"ios": {
     * 			"osVer": "12.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     *    "harmony": {
     *      "osVer": "3.0",
     *       "uniVer": "4.31",
     *       "unixVer": "4.61",
     *       "unixVaporVer": "5.0"
     *    }
     * 	},
     *   "web": {
     *     "uniVer": "x",
     *     "unixVer": "x"
     *   },
     *  "mp":{
     *    "weixin": {
     *      "hostVer": "√",
     *      "uniVer": "√",
     *      "unixVer": "4.41"
     *    },
     *    "alipay": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "baidu": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "toutiao": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "lark": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "qq": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "kuaishou": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "jd": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    }
     *  }
     * }
     */
    startSoterAuthentication(options: StartSoterAuthenticationOptions): void;
    /**
     * 获取本机支持的  生物认证方式
	 * @param options 获取本机支持的生物认证方式的参数
     *
     * @tutorial https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#checkissupportsoterauthentication
     * @tutorial_uni_app_x https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#checkissupportsoterauthentication
     * @tutorial_uni_app https://uniapp.dcloud.net.cn/api/system/authentication.html#checkissupportsoterauthentication
     *
     * @uniPlatform {
     * 	"app": {
     * 		"android": {
     * 			"osVer": "5.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     * 		"ios": {
     * 			"osVer": "12.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     *    "harmony": {
     *      "osVer": "3.0",
     *       "uniVer": "4.31",
     *       "unixVer": "4.61",
     *       "unixVaporVer": "5.0"
     *    }
     * 	},
     *   "web": {
     *     "uniVer": "x",
     *     "unixVer": "x"
     *   },
     *  "mp":{
     *    "weixin": {
     *      "hostVer": "√",
     *      "uniVer": "√",
     *      "unixVer": "4.41"
     *    },
     *    "alipay": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "baidu": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "toutiao": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "lark": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "qq": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "kuaishou": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "jd": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    }
     *  }
     * }
     */
    checkIsSupportSoterAuthentication(options: CheckIsSupportSoterAuthenticationOptions): void;
    /**
     * 获取设备内是否录入如指纹等生物信息
     *
     * @tutorial https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#checkissoterenrolledindevice
     * @tutorial_uni_app_x https://doc.dcloud.net.cn/uni-app-x/api/bio-auth.html#checkissoterenrolledindevice
     * @tutorial_uni_app https://uniapp.dcloud.net.cn/api/system/authentication.html#checkissoterenrolledindevice
     *
     * @uniPlatform {
     * 	"app": {
     * 		"android": {
     * 			"osVer": "5.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     * 		"ios": {
     * 			"osVer": "12.0",
     * 			"uniVer": "2.3.8",
     * 			"unixVer": "5.08"
     * 		},
     *    "harmony": {
     *      "osVer": "3.0",
     *       "uniVer": "4.31",
     *       "unixVer": "4.61",
     *       "unixVaporVer": "5.0"
     *    }
     * 	},
     *   "web": {
     *     "uniVer": "x",
     *     "unixVer": "x"
     *   },
     *  "mp":{
     *    "weixin": {
     *      "hostVer": "√",
     *      "uniVer": "√",
     *      "unixVer": "4.41"
     *    },
     *    "alipay": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "baidu": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "toutiao": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "lark": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "qq": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "kuaishou": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    },
     *    "jd": {
     *      "hostVer": "x",
     *      "uniVer": "x",
     *      "unixVer": "x"
     *    }
     *  }
     * }
     */
    checkIsSoterEnrolledInDevice(options: CheckIsSoterEnrolledInDeviceOptions): void;
}

export type StartSoterAuthentication = (options: StartSoterAuthenticationOptions) => void;
/**
* 生物认证方式
*/
export type SoterAuthMode =
    /**
     * 指纹识别
     */
    'fingerPrint' |
    /**
     * 人脸识别
     */
    'facial' |
    /**
     * 声纹识别（暂未支持）
     */
    'speech';

export type StartSoterAuthenticationSuccess = {
    /**
     * 错误码
     */
    errCode: number,
    /**
     * 生物认证方式
     * - fingerPrint: 指纹识别
     * - facial: 人脸识别
     * - speech: 声纹识别（暂未支持）
     */
    authMode: SoterAuthMode,
    /**
     * 在设备安全区域（TEE）内获得的本机安全信息以及本次认证信息
     */
    resultJSON?: string | null,
    /**
     * 用安全密钥对 resultJSON 的签名(SHA256 with RSA/PSS, saltlen=20)
     */
    resultJSONSignature?: string | null,
    /**
     * 接口调用结果
     */
    errMsg: string
};
export type StartSoterAuthenticationSuccessCallback = (result: StartSoterAuthenticationSuccess) => void;
export interface IStartSoterAuthenticationFail extends IUniError {
}
export type StartSoterAuthenticationFail = IStartSoterAuthenticationFail;
export type StartSoterAuthenticationFailCallback = (result: StartSoterAuthenticationFail) => void;
export type StartSoterAuthenticationComplete = StartSoterAuthenticationSuccess | StartSoterAuthenticationFail;
export type StartSoterAuthenticationCompleteCallback = (result: StartSoterAuthenticationComplete) => void;
export type StartSoterAuthenticationOptions = {
    /**
     * 请求使用的可接受的生物认证方式
     */
    requestAuthModes: SoterAuthMode[],
    /**
     * 挑战因子
     */
    challenge?: string | null,
    /**
     * 验证描述，即识别过程中显示在界面上的对话框提示内容
     */
    authContent?: string | null,
    /**
     * 接口调用成功的回调函数
     */
    success?: StartSoterAuthenticationSuccessCallback | null,
    /**
     * 接口调用失败的回调函数
     */
    fail?: StartSoterAuthenticationFailCallback | null,
    /**
     * 接口调用结束的回调函数（调用成功、失败都会执行）
     */
    complete?: StartSoterAuthenticationCompleteCallback | null
};
export type CheckIsSupportSoterAuthentication = (options: CheckIsSupportSoterAuthenticationOptions) => void;
export type CheckIsSupportSoterAuthenticationSuccess = {
    /**
     * 支持的生物认证方式
     */
    supportMode: SoterAuthMode[],
    /**
     * 接口调用结果
     */
    errMsg: string
};
export type CheckIsSupportSoterAuthenticationSuccessCallback = (result: CheckIsSupportSoterAuthenticationSuccess) => void;
export interface ICheckIsSupportSoterAuthenticationFail extends IUniError {
}
export type CheckIsSupportSoterAuthenticationFail = ICheckIsSupportSoterAuthenticationFail;
export type CheckIsSupportSoterAuthenticationFailCallback = (result: CheckIsSupportSoterAuthenticationFail) => void;
export type CheckIsSupportSoterAuthenticationComplete = CheckIsSupportSoterAuthenticationSuccess | CheckIsSupportSoterAuthenticationFail;
export type CheckIsSupportSoterAuthenticationCompleteCallback = (result: CheckIsSupportSoterAuthenticationComplete) => void;

/**
* 开始生物认证的参数
*/
export type CheckIsSupportSoterAuthenticationOptions = {
    /**
     * 接口调用成功的回调函数
     */
    success?: CheckIsSupportSoterAuthenticationSuccessCallback | null,
    /**
     * 接口调用失败的回调函数
     */
    fail?: CheckIsSupportSoterAuthenticationFailCallback | null,
    /**
     * 接口调用结束的回调函数（调用成功、失败都会执行）
     */
    complete?: CheckIsSupportSoterAuthenticationCompleteCallback | null
};
export type CheckIsSoterEnrolledInDevice = (options: CheckIsSoterEnrolledInDeviceOptions) => void;
export type CheckIsSoterEnrolledInDeviceSuccess = {
    /**
     * 是否已录入信息
     * @type boolean
     */
    isEnrolled: boolean,
    /**
     * 错误信息
     */
    errMsg: string
};
export type CheckIsSoterEnrolledInDeviceSuccessCallback = (result: CheckIsSoterEnrolledInDeviceSuccess) => void;
export interface ICheckIsSoterEnrolledInDeviceFail extends IUniError {
}
export type CheckIsSoterEnrolledInDeviceFail = ICheckIsSoterEnrolledInDeviceFail;
export type CheckIsSoterEnrolledInDeviceFailCallback = (result: CheckIsSoterEnrolledInDeviceFail) => void;
export type CheckIsSoterEnrolledInDeviceComplete = CheckIsSoterEnrolledInDeviceSuccess | CheckIsSoterEnrolledInDeviceFail;
export type CheckIsSoterEnrolledInDeviceCompleteCallback = (result: CheckIsSoterEnrolledInDeviceComplete) => void;

/**
* 获取本机支持的生物认证方式的参数
*/
export type CheckIsSoterEnrolledInDeviceOptions = {
    /**
     * 生物认证方式
     * - fingerPrint: 指纹识别
     * - facial: 人脸识别（暂未支持）
     * - speech: 声纹识别（暂未支持）
     */
    checkAuthMode: SoterAuthMode,
    /**
     * 支持的生物认证方式
     */
    success?: CheckIsSoterEnrolledInDeviceSuccessCallback | null,
    /**
     * 接口调用失败的回调函数
     */
    fail?: CheckIsSoterEnrolledInDeviceFailCallback | null,
    /**
     * 接口调用结束的回调函数（调用成功、失败都会执行）
     */
    complete?: CheckIsSoterEnrolledInDeviceCompleteCallback | null
};
