import { UASMLoader } from '../interface.uts'

/**
 * loader 由编译器注入，用户态 API 仅接收 module 参数
 */
export function loadUASM<T>(
    module: string,
    loader: UASMLoader<T> | null = null,
): Promise<T> {
    return new Promise<T>((resolve, reject) => {
        try {
            if (loader == null) {
                throw new Error(`uni.loadUASM[${module}] 参数未经过编译处理`)
            }
            resolve(loader!())
        } catch (error) {
            reject(error)
        }
    })
}
