import { UASMLoader } from '../interface.uts'

function loadLibrary(module: string): void {
    if (module.includes('/')) {
        System.load(UTSAndroid.convert2AbsFullPath(module))
        return
    }

    let libraryName = module
    if (libraryName.startsWith('lib') && libraryName.endsWith('.so')) {
        libraryName = libraryName.substring(3, libraryName.length - 3)
    }
    System.loadLibrary(libraryName)
}

/**
 * loader 由编译器注入，用户态 API 仅接收 module 参数
 */
export function loadUASM<T>(
    module: string,
    loader: UASMLoader<T> | null = null,
): Promise<T> {
    return new Promise<T>((resolve, reject) => {
        try {
            if (loader == null) {
                throw new Error(`uni.loadUASM[${module}] 参数未经过编译处理`)
            }
            loadLibrary(module)
            resolve(loader())
        } catch (error) {
            reject(error)
        }
    })
}
