export { showToast, hideToast } from './toast.uts'
// #ifndef UNI-APP-X
export { showModal } from './modal.uts'
export { showActionSheet } from './actionSheet.uts'
export { showLoading, hideLoading } from './loading.uts'
// #endif

export {
    ShowToast,
    ShowToastOptions,
    ShowToastSuccess,
    ShowToastFail,
    HideToast,
    // #ifndef UNI-APP-X
    ShowLoading,
    ShowLoadingOptions,
    ShowLoadingSuccess,
    ShowLoadingFail,
    HideLoading,
    ShowModal,
    ShowModalOptions,
    ShowModalSuccess,
    ShowModalFail,
    ShowActionSheet,
    ShowActionSheetOptions,
    ShowActionSheetSuccess,
    ShowActionSheetFail,
    // #endif
} from '../interface.uts';
