import { AccelerometerErrorCode, IStartAccelerometerFail, IStopAccelerometerFail } from './interface.uts'

export const AccelerometerUniErrorSubject = 'uni-accelerometer'

export const AccelerometerUniErrors : Map<number, string> = new Map([
	[601, 'accelerometer not supported'],
	[602, 'start accelerometer failed'],
	[603, 'stop accelerometer failed'],
	[604, 'native internal error'],
	[701, 'android sensor manager unavailable'],
	[702, 'android accelerometer unavailable'],
	[703, 'android register listener failed'],
	[801, 'ios accelerometer unavailable'],
	[802, 'ios motion manager init failed'],
	[803, 'ios start accelerometer failed'],
	[804, 'ios stop accelerometer failed'],
	[501, 'harmony accelerometer unavailable'],
	[502, 'harmony subscribe accelerometer failed'],
	[503, 'harmony unsubscribe accelerometer failed'],
	[901, 'web accelerometer unsupported']
])

export class StartAccelerometerFailImpl extends UniError implements IStartAccelerometerFail {
	override errCode : AccelerometerErrorCode

	constructor(errCode : AccelerometerErrorCode) {
		super()
		this.errCode = errCode
		this.errSubject = AccelerometerUniErrorSubject
	}
}

export class StopAccelerometerFailImpl extends UniError implements IStopAccelerometerFail {
	override errCode : AccelerometerErrorCode

	constructor(errCode : AccelerometerErrorCode) {
		super()
		this.errCode = errCode
		this.errSubject = AccelerometerUniErrorSubject
	}
}

export function createStartAccelerometerFail(errCode : AccelerometerErrorCode, errMsg : string | null = null, data : UTSJSONObject | null = null, cause : Error | null = null) : StartAccelerometerFailImpl {
	const error = new StartAccelerometerFailImpl(errCode)
	const defaultMessage = AccelerometerUniErrors.get(errCode)
	error.errMsg = errMsg != null ? errMsg : (defaultMessage != null ? defaultMessage : '')
	error.data = data
	if (cause != null) {
		error.cause = cause
	}
	return error
}

export function createStopAccelerometerFail(errCode : AccelerometerErrorCode, errMsg : string | null = null, data : UTSJSONObject | null = null, cause : Error | null = null) : StopAccelerometerFailImpl {
	const error = new StopAccelerometerFailImpl(errCode)
	const defaultMessage = AccelerometerUniErrors.get(errCode)
	error.errMsg = errMsg != null ? errMsg : (defaultMessage != null ? defaultMessage : '')
	error.data = data
	if (cause != null) {
		error.cause = cause
	}
	return error
}
