import {
    ANIMATION_TYPE,
    SWITCH_TAB,
    SwitchTabPage,
    __uniConfig,
    changeTabBarIndex,
    entryPageState,
    findPageRoute,
    getCurrentPage,
    getTabBarIndex,
    isTabPage,
    parseUrl,
    resolveAppRoute,
    switchTabPagesBeforeEntryPages,
} from '@dcloudio/uni-runtime'
import { SwitchTabOptions, SwitchTabSuccess } from '../interface.uts'

import { SwitchTabFailImpl } from '../unierror.uts'

export const switchTab = defineAsyncApi<SwitchTabOptions, SwitchTabSuccess>(
    SWITCH_TAB,
    (options: SwitchTabOptions, res: ApiExecutor) => {
        if (!entryPageState.handledBeforeEntryPageRoutes) {
            switchTabPagesBeforeEntryPages.push({ options } as SwitchTabPage)
            return
        }
        let url = options.url as string
        let info = parseUrl(url)
        let path = info.path
        if (findPageRoute(path) == null) {
            res.reject(new SwitchTabFailImpl(`page ${path} is not found`))
            return
        }
        let selected: number = getTabBarIndex(path)
        if (selected == -1) {
            res.reject(new SwitchTabFailImpl(`page ${path} is not tab page`))
            return
        }
        const currentPage = getCurrentPage()
        const shouldDispatchAppRoute =
            currentPage == null ||
            !isTabPage(currentPage!) ||
            getTabBarIndex(currentPage!.route) != selected
        const appRoute = shouldDispatchAppRoute
            ? resolveAppRoute(url, SWITCH_TAB)
            : null
        if (appRoute != null) {
            url = appRoute!.url
            info = parseUrl(url)
            path = info.path
            selected = getTabBarIndex(path)
        }
        const query = info.query
        const pages = getCurrentPages()
        setTimeout(() => {
            changeTabBarIndex(
                selected,
                path,
                query,
                false,
                SWITCH_TAB,
                appRoute?.context,
            )
            for (let index = 0; index < pages.length; index++) {
                const page = pages[index]
                if (!isTabPage(page.vm!)) {
                    page.vm!.$close(
                        new Map<string, any | null>([[ANIMATION_TYPE, 'none']]),
                    )
                }
            }
            res.resolve(null)
        }, 0)
    },
    [
        new ApiProtocol<SwitchTabOptions>(
            (options: SwitchTabOptions): UniError | null => {
                if (options.url.length == 0) {
                    return new SwitchTabFailImpl('Missing required args: "url"')
                }
                return null
            },
        ),
    ],
)
