describe('uni-wifi', () => {
  let page;
  beforeAll(async () => {
    page = await program.reLaunch('/pages/autotest/uni-wifi/uni-wifi');
    await page.waitFor(3000);
  });
  it('startWifi0', async () => {
    const result0 = await page.callMethod('startWifi00');
    expect(result0.res).not.toHaveProperty('_errMsg');
    expect(result0.res.errCode).toEqual(expect.any(Number));
    expect(result0.res.errSubject).toEqual(expect.any(String));
    expect(result0.res.errMsg).toEqual(expect.any(String));
    const result1 = await page.callMethod('startWifi01');
    expect(result1.res).not.toHaveProperty('_errMsg');
    expect(result1.res.errCode).toEqual(expect.any(Number));
    expect(result1.res.errSubject).toEqual(expect.any(String));
    expect(result1.res.errMsg).toEqual(expect.any(String));
    const result2 = await page.callMethod('startWifi02');
    expect(result2.res).not.toHaveProperty('_errMsg');
    expect(result2.res.errCode).toEqual(expect.any(Number));
    expect(result2.res.errSubject).toEqual(expect.any(String));
    expect(result2.res.errMsg).toEqual(expect.any(String));
    const result3 = await page.callMethod('startWifi03');
    expect(result3.res).not.toHaveProperty('_errMsg');
    expect(result3.res.errCode).toEqual(expect.any(Number));
    expect(result3.res.errSubject).toEqual(expect.any(String));
    expect(result3.res.errMsg).toEqual(expect.any(String));
    const result4 = await page.callMethod('startWifi04');
    expect(result4.res).not.toHaveProperty('_errMsg');
    expect(result4.res.errCode).toEqual(expect.any(Number));
    expect(result4.res.errSubject).toEqual(expect.any(String));
    expect(result4.res.errMsg).toEqual(expect.any(String));
    const result5 = await page.callMethod('startWifi05');
    expect(result5.res).not.toHaveProperty('_errMsg');
    expect(result5.res.errCode).toEqual(expect.any(Number));
    expect(result5.res.errSubject).toEqual(expect.any(String));
    expect(result5.res.errMsg).toEqual(expect.any(String));
    const result6 = await page.callMethod('startWifi06');
    expect(result6.res).not.toHaveProperty('_errMsg');
    expect(result6.res.errCode).toEqual(expect.any(Number));
    expect(result6.res.errSubject).toEqual(expect.any(String));
    expect(result6.res.errMsg).toEqual(expect.any(String));
    const result7 = await page.callMethod('startWifi07');
    expect(result7.res).not.toHaveProperty('_errMsg');
    expect(result7.res.errCode).toEqual(expect.any(Number));
    expect(result7.res.errSubject).toEqual(expect.any(String));
    expect(result7.res.errMsg).toEqual(expect.any(String));
    const result8 = await page.callMethod('startWifi08');
    expect(result8.res).not.toHaveProperty('_errMsg');
    expect(result8.res.errCode).toEqual(expect.any(Number));
    expect(result8.res.errSubject).toEqual(expect.any(String));
    expect(result8.res.errMsg).toEqual(expect.any(String));
    const result9 = await page.callMethod('startWifi09');
    expect(result9.res).not.toHaveProperty('_errMsg');
    expect(result9.res.errCode).toEqual(expect.any(Number));
    expect(result9.res.errSubject).toEqual(expect.any(String));
    expect(result9.res.errMsg).toEqual(expect.any(String));
    const result10 = await page.callMethod('startWifi010');
    expect(result10.res).not.toHaveProperty('_errMsg');
    expect(result10.res.errCode).toEqual(expect.any(Number));
    expect(result10.res.errSubject).toEqual(expect.any(String));
    expect(result10.res.errMsg).toEqual(expect.any(String));
    const result11 = await page.callMethod('startWifi011');
    expect(result11.res).not.toHaveProperty('_errMsg');
    expect(result11.res.errCode).toEqual(expect.any(Number));
    expect(result11.res.errSubject).toEqual(expect.any(String));
    expect(result11.res.errMsg).toEqual(expect.any(String));
    const result12 = await page.callMethod('startWifi012');
    expect(result12.res).not.toHaveProperty('_errMsg');
    expect(result12.res.errCode).toEqual(expect.any(Number));
    expect(result12.res.errSubject).toEqual(expect.any(String));
    expect(result12.res.errMsg).toEqual(expect.any(String));
    const result13 = await page.callMethod('startWifi013');
    expect(result13.res).not.toHaveProperty('_errMsg');
    expect(result13.res.errCode).toEqual(expect.any(Number));
    expect(result13.res.errSubject).toEqual(expect.any(String));
    expect(result13.res.errMsg).toEqual(expect.any(String));
    const result14 = await page.callMethod('startWifi014');
    expect(result14.res).not.toHaveProperty('_errMsg');
    expect(result14.res.errCode).toEqual(expect.any(Number));
    expect(result14.res.errSubject).toEqual(expect.any(String));
    expect(result14.res.errMsg).toEqual(expect.any(String));
    const result15 = await page.callMethod('startWifi015');
    expect(result15.res).not.toHaveProperty('_errMsg');
    expect(result15.res.errCode).toEqual(expect.any(Number));
    expect(result15.res.errSubject).toEqual(expect.any(String));
    expect(result15.res.errMsg).toEqual(expect.any(String));
    const result16 = await page.callMethod('startWifi016');
    expect(result16.res).not.toHaveProperty('_errMsg');
    expect(result16.res.errCode).toEqual(expect.any(Number));
    expect(result16.res.errSubject).toEqual(expect.any(String));
    expect(result16.res.errMsg).toEqual(expect.any(String));
    const result17 = await page.callMethod('startWifi017');
    expect(result17.res).not.toHaveProperty('_errMsg');
    expect(result17.res.errCode).toEqual(expect.any(Number));
    expect(result17.res.errSubject).toEqual(expect.any(String));
    expect(result17.res.errMsg).toEqual(expect.any(String));
    const result18 = await page.callMethod('startWifi018');
    expect(result18.res).not.toHaveProperty('_errMsg');
    expect(result18.res.errCode).toEqual(expect.any(Number));
    expect(result18.res.errSubject).toEqual(expect.any(String));
    expect(result18.res.errMsg).toEqual(expect.any(String));
    const result19 = await page.callMethod('startWifi019');
    expect(result19.res).not.toHaveProperty('_errMsg');
    expect(result19.res.errCode).toEqual(expect.any(Number));
    expect(result19.res.errSubject).toEqual(expect.any(String));
    expect(result19.res.errMsg).toEqual(expect.any(String));
    const result20 = await page.callMethod('startWifi020');
    expect(result20.res).not.toHaveProperty('_errMsg');
    expect(result20.res.errCode).toEqual(expect.any(Number));
    expect(result20.res.errSubject).toEqual(expect.any(String));
    expect(result20.res.errMsg).toEqual(expect.any(String));
    const result21 = await page.callMethod('startWifi021');
    expect(result21.res).not.toHaveProperty('_errMsg');
    expect(result21.res.errCode).toEqual(expect.any(Number));
    expect(result21.res.errSubject).toEqual(expect.any(String));
    expect(result21.res.errMsg).toEqual(expect.any(String));
  });
  it('stopWifi1', async () => {
    const result0 = await page.callMethod('stopWifi10');
    expect(result0.res).not.toHaveProperty('_errMsg');
    expect(result0.res.errCode).toEqual(expect.any(Number));
    expect(result0.res.errSubject).toEqual(expect.any(String));
    expect(result0.res.errMsg).toEqual(expect.any(String));
    const result1 = await page.callMethod('stopWifi11');
    expect(result1.res).not.toHaveProperty('_errMsg');
    expect(result1.res.errCode).toEqual(expect.any(Number));
    expect(result1.res.errSubject).toEqual(expect.any(String));
    expect(result1.res.errMsg).toEqual(expect.any(String));
    const result2 = await page.callMethod('stopWifi12');
    expect(result2.res).not.toHaveProperty('_errMsg');
    expect(result2.res.errCode).toEqual(expect.any(Number));
    expect(result2.res.errSubject).toEqual(expect.any(String));
    expect(result2.res.errMsg).toEqual(expect.any(String));
    const result3 = await page.callMethod('stopWifi13');
    expect(result3.res).not.toHaveProperty('_errMsg');
    expect(result3.res.errCode).toEqual(expect.any(Number));
    expect(result3.res.errSubject).toEqual(expect.any(String));
    expect(result3.res.errMsg).toEqual(expect.any(String));
    const result4 = await page.callMethod('stopWifi14');
    expect(result4.res).not.toHaveProperty('_errMsg');
    expect(result4.res.errCode).toEqual(expect.any(Number));
    expect(result4.res.errSubject).toEqual(expect.any(String));
    expect(result4.res.errMsg).toEqual(expect.any(String));
    const result5 = await page.callMethod('stopWifi15');
    expect(result5.res).not.toHaveProperty('_errMsg');
    expect(result5.res.errCode).toEqual(expect.any(Number));
    expect(result5.res.errSubject).toEqual(expect.any(String));
    expect(result5.res.errMsg).toEqual(expect.any(String));
    const result6 = await page.callMethod('stopWifi16');
    expect(result6.res).not.toHaveProperty('_errMsg');
    expect(result6.res.errCode).toEqual(expect.any(Number));
    expect(result6.res.errSubject).toEqual(expect.any(String));
    expect(result6.res.errMsg).toEqual(expect.any(String));
    const result7 = await page.callMethod('stopWifi17');
    expect(result7.res).not.toHaveProperty('_errMsg');
    expect(result7.res.errCode).toEqual(expect.any(Number));
    expect(result7.res.errSubject).toEqual(expect.any(String));
    expect(result7.res.errMsg).toEqual(expect.any(String));
    const result8 = await page.callMethod('stopWifi18');
    expect(result8.res).not.toHaveProperty('_errMsg');
    expect(result8.res.errCode).toEqual(expect.any(Number));
    expect(result8.res.errSubject).toEqual(expect.any(String));
    expect(result8.res.errMsg).toEqual(expect.any(String));
    const result9 = await page.callMethod('stopWifi19');
    expect(result9.res).not.toHaveProperty('_errMsg');
    expect(result9.res.errCode).toEqual(expect.any(Number));
    expect(result9.res.errSubject).toEqual(expect.any(String));
    expect(result9.res.errMsg).toEqual(expect.any(String));
    const result10 = await page.callMethod('stopWifi110');
    expect(result10.res).not.toHaveProperty('_errMsg');
    expect(result10.res.errCode).toEqual(expect.any(Number));
    expect(result10.res.errSubject).toEqual(expect.any(String));
    expect(result10.res.errMsg).toEqual(expect.any(String));
    const result11 = await page.callMethod('stopWifi111');
    expect(result11.res).not.toHaveProperty('_errMsg');
    expect(result11.res.errCode).toEqual(expect.any(Number));
    expect(result11.res.errSubject).toEqual(expect.any(String));
    expect(result11.res.errMsg).toEqual(expect.any(String));
    const result12 = await page.callMethod('stopWifi112');
    expect(result12.res).not.toHaveProperty('_errMsg');
    expect(result12.res.errCode).toEqual(expect.any(Number));
    expect(result12.res.errSubject).toEqual(expect.any(String));
    expect(result12.res.errMsg).toEqual(expect.any(String));
    const result13 = await page.callMethod('stopWifi113');
    expect(result13.res).not.toHaveProperty('_errMsg');
    expect(result13.res.errCode).toEqual(expect.any(Number));
    expect(result13.res.errSubject).toEqual(expect.any(String));
    expect(result13.res.errMsg).toEqual(expect.any(String));
    const result14 = await page.callMethod('stopWifi114');
    expect(result14.res).not.toHaveProperty('_errMsg');
    expect(result14.res.errCode).toEqual(expect.any(Number));
    expect(result14.res.errSubject).toEqual(expect.any(String));
    expect(result14.res.errMsg).toEqual(expect.any(String));
    const result15 = await page.callMethod('stopWifi115');
    expect(result15.res).not.toHaveProperty('_errMsg');
    expect(result15.res.errCode).toEqual(expect.any(Number));
    expect(result15.res.errSubject).toEqual(expect.any(String));
    expect(result15.res.errMsg).toEqual(expect.any(String));
    const result16 = await page.callMethod('stopWifi116');
    expect(result16.res).not.toHaveProperty('_errMsg');
    expect(result16.res.errCode).toEqual(expect.any(Number));
    expect(result16.res.errSubject).toEqual(expect.any(String));
    expect(result16.res.errMsg).toEqual(expect.any(String));
    const result17 = await page.callMethod('stopWifi117');
    expect(result17.res).not.toHaveProperty('_errMsg');
    expect(result17.res.errCode).toEqual(expect.any(Number));
    expect(result17.res.errSubject).toEqual(expect.any(String));
    expect(result17.res.errMsg).toEqual(expect.any(String));
    const result18 = await page.callMethod('stopWifi118');
    expect(result18.res).not.toHaveProperty('_errMsg');
    expect(result18.res.errCode).toEqual(expect.any(Number));
    expect(result18.res.errSubject).toEqual(expect.any(String));
    expect(result18.res.errMsg).toEqual(expect.any(String));
    const result19 = await page.callMethod('stopWifi119');
    expect(result19.res).not.toHaveProperty('_errMsg');
    expect(result19.res.errCode).toEqual(expect.any(Number));
    expect(result19.res.errSubject).toEqual(expect.any(String));
    expect(result19.res.errMsg).toEqual(expect.any(String));
    const result20 = await page.callMethod('stopWifi120');
    expect(result20.res).not.toHaveProperty('_errMsg');
    expect(result20.res.errCode).toEqual(expect.any(Number));
    expect(result20.res.errSubject).toEqual(expect.any(String));
    expect(result20.res.errMsg).toEqual(expect.any(String));
    const result21 = await page.callMethod('stopWifi121');
    expect(result21.res).not.toHaveProperty('_errMsg');
    expect(result21.res.errCode).toEqual(expect.any(Number));
    expect(result21.res.errSubject).toEqual(expect.any(String));
    expect(result21.res.errMsg).toEqual(expect.any(String));
  });
  it('connectWifi2', async () => {
    const result_assert0 = await page.callMethod('connectWifi2_assert0');
    expect(result_assert0.res).not.toHaveProperty('_errMsg');
    expect(result_assert0.res.errCode).toEqual(expect.any(Number));
    expect(result_assert0.res.errSubject).toEqual(expect.any(String));
    expect(result_assert0.res.errMsg).toEqual(expect.any(String));
  });
  it('getWifiList3', async () => {
    const result_assert0 = await page.callMethod('getWifiList3_assert0');
    expect(result_assert0.res).not.toHaveProperty('_errMsg');
    expect(result_assert0.res.errCode).toEqual(expect.any(Number));
    expect(result_assert0.res.errSubject).toEqual(expect.any(String));
    expect(result_assert0.res.errMsg).toEqual(expect.any(String));
  });
});